### ISSUE TITLE
graph.node() is null

### ISSUE THREAD

**Issue by mhkeller** [1wheel/graph-scroll#16]
When using the default example, I get an error that `graph.node(...) is null`. It seems that the graph method is required?

```js
d3.graphScroll()
    .sections(d3.selectAll('#sections > div'))
    .on('active', function(i){ console.log(i + 'th section active') })

```

**Comment by 1wheel** [comment]
Hmm... `graph.node()` is just used to get the height of the graph; if it doesn't exist I think `graphBB.height` could just be set to 0.  

https://github.com/1wheel/graph-scroll/blob/gh-pages/index.js#L53-L56

**Comment by mhkeller** [comment]
Some check to see if graph exists would be good
