### ISSUE TITLE
Publish to bower

### ISSUE THREAD

**Issue by jarandaf** [1wheel/graph-scroll#8]
And thanks for such awesome work.

**Comment by petulla** [comment]
+1 and as an npm module!

**Comment by RehanSaeed** [comment]
+1 I've been removing Bower lately and switching to NPM directly but some old projects still use it.

**Comment by 1wheel** [comment]
I made a [npm package](https://www.npmjs.com/package/graph-scroll) a few months ago. 

Haven't used bower and I'm not sure it's still worth supporting... but I'll accept a pull request if anyone needs it.
